<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_LoginWeb</name>
   <tag></tag>
   <elementGuidId>c89f0d3c-c7ce-4365-8980-77840b2e5a9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='会員の詳細情報です。'])[1]/following::b[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[href*='ad_user_front_login.action']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>143c846b-ea98-4637-abbb-cc5cb250bf51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ユーザ画面ログイン</value>
      <webElementGuid>10c7b442-588c-410f-9ca8-2c49ae08cda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pnl_content form-size&quot;]/div[@class=&quot;text-right&quot;]/a[1]/b[1]</value>
      <webElementGuid>55456099-e826-48fc-b06a-cf779eff73e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Type_Account/Login_Admin/Admin/iframe_DEV_main</value>
      <webElementGuid>e770e01f-f6ba-49d1-85cc-e0226e6e1696</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='会員の詳細情報です。'])[1]/following::b[1]</value>
      <webElementGuid>61c8d237-aecc-4651-a15c-3637c64cf900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='会員情報詳細'])[1]/following::b[1]</value>
      <webElementGuid>a4f17ba7-2d9e-4d57-ab2b-f0de60c01446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='会員情報編集'])[1]/preceding::b[1]</value>
      <webElementGuid>1404ca73-941b-4163-b9e0-26fb68c07f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ユーザ画面ログイン']/parent::*</value>
      <webElementGuid>56f52378-2281-47a0-9ff5-e7cf0df1d308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>71f77470-3a24-4923-8c93-4de72a24ec04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'ユーザ画面ログイン' or . = 'ユーザ画面ログイン')]</value>
      <webElementGuid>a9cff57a-ff33-4bb9-a2ec-3193593ada6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
