<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_DEV_main</name>
   <tag></tag>
   <elementGuidId>da55e356-c2b9-4aad-895c-f7de9ce87ffd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='frm_main']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frm_main</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6c6ecc89-c773-4a28-b15d-2d31705f59a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frm_main</value>
      <webElementGuid>d253070d-9c0d-4079-94dc-59cbfbe93cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>content_onload();</value>
      <webElementGuid>153aaeb9-f793-4716-afc4-b3ac8351eda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>ad_data_search_new.action</value>
      <webElementGuid>d83f5bc1-ed9d-46c8-a421-d0c2dd6ab4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>429a4411-fbaa-440d-965f-8f200cd9a95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>1c135ad8-02d7-4e2d-a0ce-d4d3e2354519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frm_main&quot;)</value>
      <webElementGuid>2ee392e8-7129-40cf-9467-a518161e224b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='frm_main']</value>
      <webElementGuid>27b42bbd-bc46-4b47-a503-436d1d80438d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pnl_body']/table/tbody/tr[2]/td[2]/iframe</value>
      <webElementGuid>a5152c36-2442-4504-a650-e15845af03da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/iframe</value>
      <webElementGuid>c9998970-b7d0-4211-82d9-b91d75e1b174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'frm_main' and @src = 'ad_data_search_new.action' and @name = 'main']</value>
      <webElementGuid>46e80b80-64d3-4df6-b0a3-4dbb18155ff2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
