<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_menuAcount(CM)</name>
   <tag></tag>
   <elementGuidId>e0d02203-33d1-4fc1-b34b-32a05475b454</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='scrollToTop()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.menutxt > a[href='ad_user_search.action']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>38b0076b-33c3-451d-acf3-e11575110f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>scrollToTop()</value>
      <webElementGuid>22031f32-e1e0-46a0-86d1-e09eabe1029c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>ad_user_search.action</value>
      <webElementGuid>8e301b43-5b9a-4120-8f25-b6ce4c000d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>01ed7cbb-27c4-4c4d-8897-7be88df855e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>会員管理：CM </value>
      <webElementGuid>1eb90ff9-dd5d-4681-a525-1a5d2ff67c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;obj_menu&quot;)/tbody[1]/tr[1]/td[1]/div[@class=&quot;menutxt&quot;]/a[1]</value>
      <webElementGuid>200e22c5-a72d-406e-bf63-e85593bb0f46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='scrollToTop()']</value>
      <webElementGuid>c024611d-a081-414d-9f8a-b4abd662ee6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='obj_menu']/tbody/tr/td/div/a</value>
      <webElementGuid>2e01b7cb-a9c7-4ab5-a38e-2af41993e4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'会員管理：CM')]</value>
      <webElementGuid>4ce78725-5d09-48ee-915b-48e84ec469b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹'])[1]/following::a[2]</value>
      <webElementGuid>826422b6-c173-419d-9c6b-27a87b326848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ãã®ä»–'])[1]/following::a[2]</value>
      <webElementGuid>3a1a25bb-f927-42b3-89ac-2e1de06a0de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='トライアル流入経路管理：TR'])[1]/preceding::a[1]</value>
      <webElementGuid>aded8cf7-abb0-4a16-9215-bc7773e5977b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='退会データ管理：WD'])[1]/preceding::a[2]</value>
      <webElementGuid>1e8906e9-e2fa-4b39-8b29-72aef78940bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='会員管理：CM']/parent::*</value>
      <webElementGuid>f2c4a9aa-d90e-424c-90b0-3a7b18f76306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'ad_user_search.action')]</value>
      <webElementGuid>4b098c24-e9ad-49e7-afb2-a8b209d0dcc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>30877c62-6379-450e-8884-87ddec696827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'ad_user_search.action' and (text() = '会員管理：CM ' or . = '会員管理：CM ')]</value>
      <webElementGuid>d9480810-629c-451b-8c58-080fb62fce30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
