<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_idAccount_Inlist</name>
   <tag></tag>
   <elementGuidId>1f2fa4fc-0660-4360-9ed1-ec6eb45c8c1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='if(parent)parent.scrollToTop()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>460b1957-17ce-4746-9ab1-7f68ff7a399a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(parent)parent.scrollToTop()</value>
      <webElementGuid>a091236a-c3ac-4905-9205-c9d0c14f34b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>ad_user_detail.action?id=21128</value>
      <webElementGuid>c6274310-7c66-4ecd-958b-11d770d9b51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>21128</value>
      <webElementGuid>6f5647a9-e93b-4f9a-bc2c-4047a2f272aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pnl_content&quot;]/table[@class=&quot;table-condensed&quot;]/tbody[1]/tr[1]/td[@class=&quot;text-center&quot;]/a[1]</value>
      <webElementGuid>beee569d-d569-4f8a-92ff-7ab9f81450b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Type_Account/Login_Admin/Admin/iframe_DEV_main</value>
      <webElementGuid>102e5286-5120-426f-8450-9a7259c7db8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='if(parent)parent.scrollToTop()']</value>
      <webElementGuid>1e1c4c04-2408-4cf8-ae65-f71553fcae9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'21128')]</value>
      <webElementGuid>f924434e-709e-43c5-9ac5-3eac7fd609a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='会員権限'])[1]/following::a[1]</value>
      <webElementGuid>9a247673-a0b0-4fff-a6a3-ef554488b5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='検索条件DL'])[1]/following::a[1]</value>
      <webElementGuid>d1cc30ea-cc4f-4683-b20c-9d892ac39ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST-1 xXx'])[1]/preceding::a[1]</value>
      <webElementGuid>35cbf87e-0f3e-42ad-87bd-f47b76741af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST-1'])[1]/preceding::a[1]</value>
      <webElementGuid>e37c2110-9d12-4f3b-800b-4fc91a298c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='21128']/parent::*</value>
      <webElementGuid>8bbad6b3-da4b-45de-92fc-c6249d015d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'ad_user_detail.action?id=21128')]</value>
      <webElementGuid>6c8ebb0d-2916-48ff-993b-37d6f236fc9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/a</value>
      <webElementGuid>7c329330-f4dc-4bb3-8542-2e7fc7cc8f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'ad_user_detail.action?id=21128' and (text() = '21128' or . = '21128')]</value>
      <webElementGuid>fd18c384-8a97-45cf-a85f-f1ae9b2bbe0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
