<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rdo_All_Account</name>
   <tag></tag>
   <elementGuidId>b4836e6c-6d9e-4010-b648-82ac1cbf1241</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='USER_TYPE0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#USER_TYPE0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab57e9b4-997e-489a-934a-04b293043d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>437a4adf-1c22-40c4-b796-b634d400675e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>USER_TYPE</value>
      <webElementGuid>5aaecef9-44a7-4def-ae0b-db01f87e6bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USER_TYPE0</value>
      <webElementGuid>28027a6b-bab3-4de7-b6f6-4c050cd84a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>83a6fe18-694b-4f56-85d0-51b4c8134948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USER_TYPE0&quot;)</value>
      <webElementGuid>0ce20a99-fc29-4a9a-b859-f58df59b6a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Type_Account/Login_Admin/Admin/iframe_DEV_main</value>
      <webElementGuid>cc6e0acb-fea5-4022-a912-0a34c0e2ab86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='USER_TYPE0']</value>
      <webElementGuid>1601fd4d-a50b-468a-9f11-dab5d2befbb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='datasearch']/table/tbody/tr[10]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>104cf194-bda7-48ae-a3d1-824324bf1689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>3ce22ded-2f6a-47e1-87ca-00cdbeacb96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'USER_TYPE' and @id = 'USER_TYPE0']</value>
      <webElementGuid>6c65535f-862c-49a5-9898-4a3eb514ab83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
