<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_inputEmail</name>
   <tag></tag>
   <elementGuidId>97ac6207-deb7-4252-b303-1e1ae4a9da13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='USER_EMAIL']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#USER_EMAIL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36f6c6a4-d4d1-4186-9baf-3e6fb1053d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>47927542-36fe-4480-8bd2-783913ed6787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>USER_EMAIL</value>
      <webElementGuid>1316ef87-32d7-4d7c-bf82-f6cc0b00ebb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>939a93e8-8b97-4dab-911e-314cd05becf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USER_EMAIL</value>
      <webElementGuid>fcb316c2-75f5-42b2-8e8d-61779faed16d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USER_EMAIL&quot;)</value>
      <webElementGuid>694f4c2e-7690-4675-96db-628bd37d0106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Type_Account/Login_Admin/Admin/iframe_DEV_main</value>
      <webElementGuid>fde79654-7943-4f11-b5aa-61549657fae9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='USER_EMAIL']</value>
      <webElementGuid>f65f2e00-d3d1-44ad-8473-258bdb358f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='datasearch']/table/tbody/tr[5]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>721fee17-8292-4232-871e-d0d23585a3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>98de717b-7a1b-4892-b522-9aad5b9e0399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'USER_EMAIL' and @id = 'USER_EMAIL']</value>
      <webElementGuid>0520fc9d-a4e4-4636-8e78-50112d7dd6bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
