<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_checkALLitem_area(c)</name>
   <tag></tag>
   <elementGuidId>34a48d5c-1f4f-40b8-83ab-20e47fa8d5ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-area-on</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='js-area-on']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>fd115e6d-de9b-434d-a0a1-346ff41edc0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-area-on</value>
      <webElementGuid>0684a1ec-a77f-4442-ac40-a1b470848bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>both-item-search__btn--check-on-all</value>
      <webElementGuid>f8ab0fc8-2602-4ed6-8836-d367389dbd4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-area-on&quot;)</value>
      <webElementGuid>e992b399-56bb-4c08-94c3-cf665ad77bbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='js-area-on']</value>
      <webElementGuid>297285e5-2bae-4c64-baaa-67f409989958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dataSearch']/div/div/div/div/p[3]</value>
      <webElementGuid>06e134a7-c59e-432d-b01e-0a80d7c38621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]</value>
      <webElementGuid>9895d1d3-d3d1-4f6a-a2cc-ee2bde573c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'js-area-on']</value>
      <webElementGuid>311d0bba-9e02-46d0-b30e-69165289e962</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
