<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_uncheckALLitem_Area(c)</name>
   <tag></tag>
   <elementGuidId>90ef3278-d484-4f9c-8395-9526c5ef4608</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-area-off</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='js-area-off']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ac518127-9cc3-4c2b-a5a1-eada28784a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-area-off</value>
      <webElementGuid>6204a31c-4b98-4227-8017-e2afdada184d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>both-item-search__btn--check-off-all</value>
      <webElementGuid>334dd4c1-2047-44b6-a34d-00d424366dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-area-off&quot;)</value>
      <webElementGuid>784bab0f-d8e3-4bd4-8c68-114529e56af1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='js-area-off']</value>
      <webElementGuid>d2144590-62c5-4dfd-8e9f-02255d6ebf51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dataSearch']/div/div/div/div/p[2]</value>
      <webElementGuid>908c5b68-a446-4303-9e6e-85ef606214f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>f82ff5ac-7593-4a25-82ee-a26a55abe8d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'js-area-off']</value>
      <webElementGuid>81ca3f68-0f3d-477b-b1f4-b5f8258ef4e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
