<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SelectedItem_Budget</name>
   <tag></tag>
   <elementGuidId>3a882e68-2abd-4af1-99ef-c96466ea33b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-organ-btn > span.nk-btn-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='js-organ-btn']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>93bee8de-bd66-4300-9fdc-026eff76695f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-btn-inner</value>
      <webElementGuid>1a8fb648-07e3-47c9-982e-91231186a9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>変更する</value>
      <webElementGuid>20d80abb-7d50-4573-856a-a6f60229d5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-organ-btn&quot;)/span[@class=&quot;nk-btn-inner&quot;]</value>
      <webElementGuid>17a4ec00-5ca3-4828-9600-2992f581d8d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='js-organ-btn']/span</value>
      <webElementGuid>35532a34-4c13-4bc7-8678-be26a7c746ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='全てを選択'])[1]/following::span[1]</value>
      <webElementGuid>09f4d9dd-f1aa-4072-a5d6-65b06e85dd1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='全ての選択を解除'])[1]/following::span[1]</value>
      <webElementGuid>873d0ea0-5397-4bb1-ae03-af234976e522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='再検索'])[1]/preceding::span[1]</value>
      <webElementGuid>f5f3dd13-056c-4931-af51-b998fa9a5c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='中央省庁'])[1]/preceding::span[2]</value>
      <webElementGuid>9bba562b-fcdd-4ee1-8531-34db5d2fe9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='変更する']/parent::*</value>
      <webElementGuid>07329c68-b094-4ee1-a76e-74be77f01915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/a/span</value>
      <webElementGuid>7a53af07-6d42-47d0-867f-fbdd18c330af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '変更する' or . = '変更する')]</value>
      <webElementGuid>1b5221c6-33ed-4b52-a0fa-63ee1938f983</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
