<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_submitSearch_BlockID(c)</name>
   <tag></tag>
   <elementGuidId>5507edcd-868d-4c98-be44-454ae8c2c152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-block-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='js-block-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e698394-9410-42be-ac77-0d4d74f698f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-btn both-item-search__btn--submit</value>
      <webElementGuid>6b1cc3bf-0ca3-4987-bd00-5d50b54183e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-block-btn</value>
      <webElementGuid>b1fe0c06-324f-43bd-8b0b-e7575e8b99cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>変更する</value>
      <webElementGuid>c1ef3af3-b7cb-4a4b-b37a-5c3cef00c3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-block-btn&quot;)</value>
      <webElementGuid>ea60c72e-bdef-4f66-8bc6-5770a475656d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='js-block-btn']</value>
      <webElementGuid>d19668eb-adfd-4016-b441-33dd401ac0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-block__medium-list']/div[377]/a</value>
      <webElementGuid>ab9e4a4c-af8f-489d-9233-936eb9396ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='※入札情報において、青文字部分は検索に反映されますが、メール配信には適用されません。※落札情報において、青文字部分は区市町村のみ検索に反映されます。'])[1]/following::a[1]</value>
      <webElementGuid>e991e975-5f84-41ed-91d7-d91c8b912c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='沖縄都市モノレール株式会社'])[1]/following::a[1]</value>
      <webElementGuid>8ba6ce84-151c-4933-8f6c-afecf1399cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='食品'])[1]/preceding::a[1]</value>
      <webElementGuid>f51fd3b7-a817-494c-b91b-9f6354beb260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[377]/a</value>
      <webElementGuid>21d54d83-fc02-4d91-af6c-1d7f25bd50a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'js-block-btn' and (text() = '変更する' or . = '変更する')]</value>
      <webElementGuid>bb1cc9b2-47a2-4e68-aab0-c00a12ed4171</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
