<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_checkALLitem_BlockID(c)</name>
   <tag></tag>
   <elementGuidId>feeeed46-342a-473d-8225-1a4ca1221cba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-block-on</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='js-block-on']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6d1ef0e4-afd8-4f2d-92ad-8638563f0968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-block-on</value>
      <webElementGuid>348613bb-5ad2-4f80-a6b8-dff15990e39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yotei-search__btn--check-on-all</value>
      <webElementGuid>63b90b35-fdaa-4ab7-bd65-449acb4c1762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-block-on&quot;)</value>
      <webElementGuid>bc44e9d8-3050-44fa-8a53-63cab545bebe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='js-block-on']</value>
      <webElementGuid>061b1099-0698-4919-b3bb-1b9cd161cfcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='default_block']/div/div/div/p[3]</value>
      <webElementGuid>6d894237-6174-4302-8252-28ef87c1c2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/p[3]</value>
      <webElementGuid>5aec5e38-b9c2-4bf6-9020-ee0b3cef63df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'js-block-on']</value>
      <webElementGuid>e937d27d-9fc2-4ef2-b93d-4a31783c56d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
