<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_anken_Both</name>
   <tag></tag>
   <elementGuidId>9b7aab7e-5691-4ece-958a-3041651530a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//li[@onclick='change_search_type(this)'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f706ae83-b287-421f-9758-9c4742de9fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mode</name>
      <type>Main</type>
      <value>all</value>
      <webElementGuid>ecd1cf02-e231-4fc0-9eb6-9be86cff1b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>change_search_type(this)</value>
      <webElementGuid>f5a4f22d-6728-47c0-8207-3cdcccb11ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-tab-menu__item</value>
      <webElementGuid>9d66c52a-c207-4e59-9da0-313c67cd9298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                入札・落札同時に表示
                            </value>
      <webElementGuid>c0648975-f295-49c1-a9b6-5eebb6fa99e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frm&quot;)/div[@class=&quot;item-search&quot;]/div[@class=&quot;bookmark-anken&quot;]/section[@class=&quot;nk-tab-menu__wrap&quot;]/ul[@class=&quot;js-nk-tab-menu nk-tab-menu tab_menu nk-tab-menu--4col&quot;]/li[@class=&quot;nk-tab-menu__item&quot;]</value>
      <webElementGuid>d853c0e6-766c-4386-a385-f873d9f40035</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//li[@onclick='change_search_type(this)'])[2]</value>
      <webElementGuid>f67e2aad-68cd-4bea-a24a-ce1453c30cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm']/div/div/section[2]/ul/li[2]</value>
      <webElementGuid>dce59ecc-bcb0-412b-ad47-eb47c89a1069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='予定情報のみ表示'])[1]/following::li[1]</value>
      <webElementGuid>326e52d7-a179-4a4b-970b-1c26cbe624b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ブックマーク'])[3]/following::li[2]</value>
      <webElementGuid>b7f0d174-0f13-4509-a0f6-86780f5106d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='入札情報のみ表示'])[1]/preceding::li[1]</value>
      <webElementGuid>22a59f5b-4b27-43da-9b53-1c8efd6d70ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/ul/li[2]</value>
      <webElementGuid>d19bc2df-454c-40d3-a9e5-e34593f0249f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
                                入札・落札同時に表示
                            ' or . = '
                                入札・落札同時に表示
                            ')]</value>
      <webElementGuid>160621ed-bfbf-4c25-9439-2c4c7736a20d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
