<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_anken_Nyusatsu</name>
   <tag></tag>
   <elementGuidId>6b4377ca-dc3d-47c5-b0f4-7bd37af0520d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//li[@onclick='change_search_type(this)'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>51dd7600-e667-4f03-b471-116657da40d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mode</name>
      <type>Main</type>
      <value>nyusatsu</value>
      <webElementGuid>bd75e0b5-d21a-4fd9-88a6-6776e9dc970f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>change_search_type(this)</value>
      <webElementGuid>5e870040-6f9e-4499-893b-5a96de5c468a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-tab-menu__item</value>
      <webElementGuid>8e789ced-8bde-48c9-ae1e-8b6ce5a1bf2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                入札情報のみ表示
                            </value>
      <webElementGuid>dc9d662e-10be-47fb-97df-a47df087671d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frm&quot;)/div[@class=&quot;item-search&quot;]/div[@class=&quot;bookmark-anken&quot;]/section[@class=&quot;nk-tab-menu__wrap&quot;]/ul[@class=&quot;js-nk-tab-menu nk-tab-menu tab_menu nk-tab-menu--4col&quot;]/li[@class=&quot;nk-tab-menu__item&quot;]</value>
      <webElementGuid>49c51414-aacf-4c52-ae62-9f48a914d7db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//li[@onclick='change_search_type(this)'])[3]</value>
      <webElementGuid>e05cf0ca-287f-4b57-94f8-9e738545dfd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm']/div/div/section[2]/ul/li[3]</value>
      <webElementGuid>29a6defc-8014-4097-87b4-0ee826c1e1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='入札・落札同時に表示'])[1]/following::li[1]</value>
      <webElementGuid>a6f3cfd0-8dd7-4e66-834a-77f1d5fc7be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='予定情報のみ表示'])[1]/following::li[2]</value>
      <webElementGuid>83f98aa6-0e10-4a53-962b-9afcaef9fde4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='落札情報のみ表示'])[1]/preceding::li[1]</value>
      <webElementGuid>95d607b4-817e-49cc-a1ae-b7ca0dd88464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/ul/li[3]</value>
      <webElementGuid>e47a600d-80a3-410a-9b1b-5edd09eaccd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
                                入札情報のみ表示
                            ' or . = '
                                入札情報のみ表示
                            ')]</value>
      <webElementGuid>ea9a8c85-3698-41d7-8375-9731537aa68a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
