<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Categories_Both</name>
   <tag></tag>
   <elementGuidId>be2c4038-c860-4cb7-a061-84eacc9c8832</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.nk-btn.both-item-search__btn--category.js-category-open</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='searchForm']/section[3]/div/div[2]/div/div[2]/div[2]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2b22667b-2ef0-43f5-9ade-52a17e28d9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-btn both-item-search__btn--category js-category-open</value>
      <webElementGuid>c1c92e8b-3b0f-4cb2-ada1-9e508709bc59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>業種カテゴリを選択</value>
      <webElementGuid>4b69ffe7-5a9a-4f9e-829f-cc0978ee1148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchForm&quot;)/section[@class=&quot;sec both-item-search js-nk-tab-menu-content&quot;]/div[@class=&quot;both-item-search__inner&quot;]/div[@class=&quot;both-item-search__f both-item-search__f--nyusatsu&quot;]/div[@class=&quot;both-item-search__f-box-wrap&quot;]/div[@class=&quot;both-item-search__f-box&quot;]/div[@class=&quot;both-item-search__f-box-r&quot;]/div[@class=&quot;both-item-search__category&quot;]/label[@class=&quot;nk-btn both-item-search__btn--category js-category-open&quot;]</value>
      <webElementGuid>33a9710b-1f74-401c-aa71-a5a0d9b3113a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchForm']/section[3]/div/div[2]/div/div[2]/div[2]/div/label</value>
      <webElementGuid>1ecefd4d-9b2b-4d95-8497-04498de20cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='業種カテゴリ'])[1]/following::label[1]</value>
      <webElementGuid>edcd1a6a-c922-49ed-8e93-c3b2842a2ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='発注地域を選択'])[1]/following::label[1]</value>
      <webElementGuid>4252304a-c004-4f1c-9afe-eb9780ce5abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='入札種別'])[1]/preceding::label[1]</value>
      <webElementGuid>20154482-e6c5-4151-b8ef-b4c74b36bd75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/label</value>
      <webElementGuid>676ffda6-f9ba-4157-95af-eca5b7f06e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '業種カテゴリを選択' or . = '業種カテゴリを選択')]</value>
      <webElementGuid>753abd6e-c539-402c-8e79-50730e3672db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
