<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_uncheckAllItem_BlockID(c)</name>
   <tag></tag>
   <elementGuidId>a37cb7db-d84f-4828-a333-492a76f3b035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-block-off</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='js-block-off']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8ae87509-ebeb-4393-9e7b-b5b1542a81f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-block-off</value>
      <webElementGuid>e3057312-3fdc-4c39-97d1-46155085691b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yotei-search__btn--check-off-all</value>
      <webElementGuid>ba6dcbf1-7d37-4737-9fad-463161805505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-block-off&quot;)</value>
      <webElementGuid>522a74ef-ad6b-4654-ada4-be1a9f57096c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='js-block-off']</value>
      <webElementGuid>573e8530-53cf-44a1-bb1e-166e2bd71edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='default_block']/div/div/div/p[2]</value>
      <webElementGuid>5b37e18c-e053-4386-97e3-355e1e365b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/p[2]</value>
      <webElementGuid>9fad6d81-0777-48ff-9bbf-ff95d0b4a2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'js-block-off']</value>
      <webElementGuid>f5c6191f-ecb4-4f5b-a2ac-b496a7591bbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
