<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_downloadCSV(c)</name>
   <tag></tag>
   <elementGuidId>0e82848e-0d1e-4f4c-9861-c673041581e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#export_csv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='export_csv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>224f4ec6-cef7-4d83-a90b-12834366d232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>popover-csv</value>
      <webElementGuid>84a420ae-e36e-4cb2-aeaf-2c4e9c74fe44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>export_csv</value>
      <webElementGuid>b5e8f595-b76b-4381-a909-0246b794b6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-btn nk-btn--csv yotei-item-search__btn--csv popover-about</value>
      <webElementGuid>91a61119-9ddb-481b-94bd-8add1b4cd39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CSV保存</value>
      <webElementGuid>763e3d33-3fd1-4434-bdd6-87bc1f519f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;export_csv&quot;)</value>
      <webElementGuid>013fc928-74eb-4a93-ae29-4ce0f2730044</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='export_csv']</value>
      <webElementGuid>dff0f9d1-401f-49de-8d4b-6d84e4e04910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchResultContent']/div/div/div[2]/div/a</value>
      <webElementGuid>7db70d7d-b609-437a-aebd-64b43f00387c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='この検索条件で上書き保存'])[2]/following::a[1]</value>
      <webElementGuid>7e9d287c-b5bd-466b-b482-a3d2f9096e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='この検索条件を新規追加'])[2]/following::a[2]</value>
      <webElementGuid>eaba2165-aecc-4627-ac5e-ed1dda882e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>fa8d9e1d-29cb-41b8-a2b9-42d248b5de62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'export_csv' and (text() = 'CSV保存' or . = 'CSV保存')]</value>
      <webElementGuid>aa58ce71-ba49-4917-b7d2-50a3045b2b9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
