<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_anken_yotei</name>
   <tag></tag>
   <elementGuidId>478be7c6-a036-4e1e-a001-55a8573f433c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.nk-tab-menu__item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@onclick='change_search_type(this)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>65a09818-bad3-461d-86cf-ad0ed6808940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mode</name>
      <type>Main</type>
      <value>yotei</value>
      <webElementGuid>2d570bd4-32f8-433f-abe1-001841d20d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>change_search_type(this)</value>
      <webElementGuid>29a9378e-b823-4cee-9223-ec02132bec3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-tab-menu__item</value>
      <webElementGuid>1fbad73d-9843-4591-b834-74b2b13e9b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                予定情報のみ表示
                            </value>
      <webElementGuid>78bfbb0e-d4a1-4dcc-b41a-b193ca580e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frm&quot;)/div[@class=&quot;item-search&quot;]/div[@class=&quot;bookmark-anken&quot;]/section[@class=&quot;nk-tab-menu__wrap&quot;]/ul[@class=&quot;js-nk-tab-menu nk-tab-menu tab_menu nk-tab-menu--4col&quot;]/li[@class=&quot;nk-tab-menu__item&quot;]</value>
      <webElementGuid>9c6c1565-c3f6-41c7-b1eb-73f1b6f75fad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@onclick='change_search_type(this)']</value>
      <webElementGuid>8f9b7dbf-1e0a-469c-9110-22db18ed676f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm']/div/div/section[2]/ul/li</value>
      <webElementGuid>cf32a2d2-41d0-4d75-95bc-a0cdf96981c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ブックマーク'])[3]/following::li[1]</value>
      <webElementGuid>f1de9745-7e96-460e-bec3-e1e2cc6978b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ブックマーク'])[2]/following::li[1]</value>
      <webElementGuid>906ffd14-86d9-42a3-b7e5-07991ca0cbce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='入札・落札同時に表示'])[1]/preceding::li[1]</value>
      <webElementGuid>d81ec7d4-4588-42a9-b05d-35bed20cf053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/ul/li</value>
      <webElementGuid>bb337f41-442d-4a9e-b426-ccf92a8df5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
                                予定情報のみ表示
                            ' or . = '
                                予定情報のみ表示
                            ')]</value>
      <webElementGuid>88a815a6-295e-455d-9f10-c8b91a93a53a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
