<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_RemoveTextboxOR</name>
   <tag></tag>
   <elementGuidId>e6ecd761-3794-4152-984e-3d25332a7a2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subjectORInput_Shrink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button_login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3592b80d-cfe7-48a6-8dff-eb18060cb99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>84d26150-d69a-4f56-a798-f1b5ece7c7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_login</value>
      <webElementGuid>5ca5a25b-cb10-4d44-a009-f95e2bf864f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-block btn-primary</value>
      <webElementGuid>d5be1a43-d98f-4f34-9cd8-4c4f3a2d3327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ログイン</value>
      <webElementGuid>2b6bea60-08de-495e-a4f2-acb325b10ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_login&quot;)</value>
      <webElementGuid>cf308ba1-b19f-406c-b37a-c70009dbadcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button_login']</value>
      <webElementGuid>88952e32-787a-485a-babd-4439218b9e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_login']/div[3]/button</value>
      <webElementGuid>88bc34de-df9d-42b0-bb79-1cb52c7de75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>2ec18f3a-cab6-4edf-a0a0-c39f3f87fd7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address'])[1]/following::button[1]</value>
      <webElementGuid>0e2aa8ba-a31f-41e9-b2c5-62b2b0c2bfc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='パスワードをお忘れになった方'])[1]/preceding::button[1]</value>
      <webElementGuid>6b3a196a-6706-43bd-b03b-8b55ac12a8d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ログインのできない方'])[1]/preceding::button[1]</value>
      <webElementGuid>5e0acff4-41bc-4ae3-99fd-2ec1a3f88a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ログイン']/parent::*</value>
      <webElementGuid>fe446b64-f919-44b4-b884-876c026f15ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>01818275-6c7c-40a9-a83c-ba0ef40b6c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'button_login' and (text() = 'ログイン' or . = 'ログイン')]</value>
      <webElementGuid>a2d3e634-54cd-409a-837e-0b099c37ee65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
