<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_close(X)_popup_Budget</name>
   <tag></tag>
   <elementGuidId>d5e7ddf6-658c-44de-b395-7e56e3342d5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.modal__close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ab5f853c-457a-4e1c-a6e1-d1dfc92aae3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>498a9c7f-e797-4fac-b93d-4661c7bc10e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal__close</value>
      <webElementGuid>686ca88e-3018-4b30-9c8d-21f7f1565590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close modal</value>
      <webElementGuid>1b301468-5d0f-4daa-bb85-4f8fa9c82f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-organ&quot;)/div[@class=&quot;modal__overlay pref-select&quot;]/div[@class=&quot;modal__container&quot;]/header[@class=&quot;modal__header on&quot;]/button[@class=&quot;modal__close&quot;]</value>
      <webElementGuid>ff5d9b1b-378c-4f73-9da1-f54c2f381f40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>d3b84fce-5779-4e26-ae8a-8c6203872926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-organ']/div/div/header/button[3]</value>
      <webElementGuid>984de358-ab9f-4e23-873f-3b69eb1f6e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>acb64241-d6ee-492d-a353-562bf477caaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>953026dc-9348-47cf-92bf-2baa1b2d79e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
