<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_submitSearch(c)</name>
   <tag></tag>
   <elementGuidId>3edeb2ec-370c-49d9-94b3-713df144f0b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_form_submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_form_submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6216eb52-352d-4aca-81f1-f42e3021100e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-btn</value>
      <webElementGuid>943087d4-79d4-42e0-b28a-e5335a61122a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_form_submit</value>
      <webElementGuid>da23ea75-2f44-4682-8a04-0007bf6ced79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>検索する</value>
      <webElementGuid>3bfbd558-e5fe-400e-ac02-2efbd9e30b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_form_submit&quot;)</value>
      <webElementGuid>3508097b-4bec-4697-a838-98dbb17554f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_form_submit']</value>
      <webElementGuid>fa46e340-6d06-4157-8df5-57132d1e735f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchbox']/div/div/div/div[2]/a</value>
      <webElementGuid>8bdda991-6b76-46e3-8d17-28450ebffd6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='検索キーワード'])[1]/following::a[1]</value>
      <webElementGuid>7f370e3a-1886-4075-931b-219d1e2997d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='機関選択'])[2]/following::a[1]</value>
      <webElementGuid>faf16e40-c60f-40bd-bf7c-10c0f48421fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='予算書　検索結果:'])[1]/preceding::a[1]</value>
      <webElementGuid>eb2e46ce-a121-402a-927b-c3cd3397e3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>64b135f0-b4ff-4d18-ab83-2711ae6072eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_form_submit' and (text() = '検索する' or . = '検索する')]</value>
      <webElementGuid>69a92730-a0cc-4312-abf6-fdda481b7c86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
