<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_AddTextboxAnd</name>
   <tag></tag>
   <elementGuidId>30c8951d-c66f-48e2-86e8-6650bd77ef0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subjectANDInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button_login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a375cec-5f7e-4cf0-809c-eb41abcbb55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>137e460f-2f19-4925-a958-ea3224cb23e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_login</value>
      <webElementGuid>ed80e35d-ee1b-4a0c-b69d-f93889a17290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-block btn-primary</value>
      <webElementGuid>c62c7e2e-bf25-4888-91e6-56717e02dba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ログイン</value>
      <webElementGuid>50381146-cd54-4128-a55e-f0ea75aaa8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_login&quot;)</value>
      <webElementGuid>915e49a4-38de-460b-8da5-01225980d11d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button_login']</value>
      <webElementGuid>21ea40b6-e12d-4082-b2f1-1a3893b072d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_login']/div[3]/button</value>
      <webElementGuid>73eb4da3-bb25-44c5-bb41-285dd538c9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>00fad688-6363-48b9-9b2c-7b4423dd164d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address'])[1]/following::button[1]</value>
      <webElementGuid>aa60927c-23ec-469a-904c-89fa761d03c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='パスワードをお忘れになった方'])[1]/preceding::button[1]</value>
      <webElementGuid>1f6427d8-85b2-4442-a48d-edff9018767e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ログインのできない方'])[1]/preceding::button[1]</value>
      <webElementGuid>6c89c55d-2ab6-4263-a1a0-6aaf6fd1f959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ログイン']/parent::*</value>
      <webElementGuid>4f8ccfdf-aeb5-42cd-9dde-26e2455965e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>b77d1dff-b714-44a9-92a9-8310119f2dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'button_login' and (text() = 'ログイン' or . = 'ログイン')]</value>
      <webElementGuid>14514c49-ed8f-4cc1-a845-86bd0ba8d2b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
