<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_leftitem2_Budget</name>
   <tag></tag>
   <elementGuidId>35b50d9d-4373-48e9-8ab6-387f3a591249</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#organ_high3 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='organ_high3']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c2b8a64-5fa9-4a84-a554-7382a6c40bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:scrollController.scrollTo('#js-block__medium-list_3')</value>
      <webElementGuid>3f74ec07-5904-4592-a492-a6fa5816008f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3d92eb77-5083-45f2-8f72-c5418255abd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>都道府県庁</value>
      <webElementGuid>1aaac4f4-9100-4269-a85c-917ac47de7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organ_high3&quot;)/a[1]</value>
      <webElementGuid>4fe9c617-a31a-4e28-a60f-ef96b3bc0cf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='organ_high3']/a</value>
      <webElementGuid>026b4ef6-92f7-43fb-a465-4de861c68cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'都道府県庁')]</value>
      <webElementGuid>9f83b8f2-37dc-466a-8b89-2fed1a8b62a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='中央省庁'])[1]/following::a[1]</value>
      <webElementGuid>2256142b-7680-4cda-8e8d-e6966c66dd60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='再検索'])[1]/following::a[2]</value>
      <webElementGuid>15bff6d2-b042-4ad5-8b9c-af859a47adc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='区市町村'])[1]/preceding::a[1]</value>
      <webElementGuid>5714a963-1fb4-471c-aa98-dee6d044e7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='衆議院'])[1]/preceding::a[3]</value>
      <webElementGuid>5fecd4af-a337-4917-a105-743f15eaf715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='都道府県庁']/parent::*</value>
      <webElementGuid>bc138cc4-663c-4cb3-8478-b86eac9e6ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:scrollController.scrollTo('#js-block__medium-list_3')&quot;)]</value>
      <webElementGuid>d26ebeb1-c43c-4161-b989-31d765d596de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>1c3bbcbe-6be9-4613-bc0e-90a798c63600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:scrollController.scrollTo(&quot; , &quot;'&quot; , &quot;#js-block__medium-list_3&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '都道府県庁' or . = '都道府県庁')]</value>
      <webElementGuid>06b7983e-edd2-4073-9aa0-b52152eca1a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
