<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_leftitem1_Budget</name>
   <tag></tag>
   <elementGuidId>a9b8bec8-a7e8-411b-810f-bda90d7e2653</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#organ_high1 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='organ_high1']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e7e116d-f448-4197-bbca-da6ed8881dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:scrollController.scrollTo('#js-block__medium-list_1')</value>
      <webElementGuid>1c19fc7e-884e-4cf8-ac26-fdf8557f45d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>721c37ce-e7f8-4703-aeae-5b587f1a88e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>中央省庁</value>
      <webElementGuid>138a1c4e-ed3b-4d9b-9c90-689054dcdb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organ_high1&quot;)/a[1]</value>
      <webElementGuid>c75f3472-a9da-40d9-a07c-9142972993f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='organ_high1']/a</value>
      <webElementGuid>26ed670d-62e2-4156-81d6-8a5ca9b6f0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'中央省庁')]</value>
      <webElementGuid>5c33fe77-bf8e-4c3e-a5f9-e5032c482010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='再検索'])[1]/following::a[1]</value>
      <webElementGuid>7f7dbbd3-9822-4b2a-af83-868fbe30b77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='変更する'])[1]/following::a[2]</value>
      <webElementGuid>ef79627a-0fc9-4b96-a95c-b4d5c45728cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='都道府県庁'])[1]/preceding::a[1]</value>
      <webElementGuid>0cafef1f-760d-4ab8-86a5-2ee71f926e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='区市町村'])[1]/preceding::a[2]</value>
      <webElementGuid>fbf0ec1d-9d9e-466a-bbf0-a5fca339fbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='中央省庁']/parent::*</value>
      <webElementGuid>1ae34683-8574-4a07-b9c8-44d34ed61daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:scrollController.scrollTo('#js-block__medium-list_1')&quot;)]</value>
      <webElementGuid>d4c5e0a6-3d5c-4ac1-a0fe-bbfb5b078405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/ul/li/a</value>
      <webElementGuid>f7d88111-f3b4-4dc4-b13b-a79c941ba898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:scrollController.scrollTo(&quot; , &quot;'&quot; , &quot;#js-block__medium-list_1&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '中央省庁' or . = '中央省庁')]</value>
      <webElementGuid>e9d4c0fb-e3f3-4af9-8d39-e1ebfbbe2f1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
