<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_checkbox_blockID</name>
   <tag></tag>
   <elementGuidId>fc270baa-6008-4cd0-946e-e3df79a02dad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='block__medium' and @id='js-block__medium-list']/div//input[@type='checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//div[@class='block__medium' and @id='js-block__medium-list']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d2ff7786-a13a-423a-828a-690b8ffe4e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modal-login</value>
      <webElementGuid>76ec0fcd-247d-42b2-b5eb-29cc09258924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>9ee1a2ff-7e6b-4cb6-ac13-cc66ccf8e521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5b9c5858-a384-4e32-991a-c779e150bd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>会員ログイン</value>
      <webElementGuid>9295fd33-cf24-44c2-bbea-03eee77fb7b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global&quot;)/ul[1]/li[@class=&quot;nav-link--login&quot;]/a[1]</value>
      <webElementGuid>5dc83be5-8fe6-4935-86a0-44a7b17a8937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='global']/ul/li[8]/a</value>
      <webElementGuid>5e5a5865-ee87-4170-8b66-bd6415b843ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'会員ログイン')])[2]</value>
      <webElementGuid>ae6f7bd7-25a9-445d-a41f-fbadb43a16fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='お問い合わせフォーム'])[1]/following::a[2]</value>
      <webElementGuid>7aef46be-63da-4f7b-804a-f37a993f766c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='入札情報速報掲載'])[1]/preceding::a[1]</value>
      <webElementGuid>d6b8399b-325d-4943-b773-876603b3bee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[12]</value>
      <webElementGuid>d9f457b8-2f74-49fc-8a98-ea935ab3d7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>81a1bdce-2b3a-414f-9413-ca9c4b500775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '会員ログイン' or . = '会員ログイン')]</value>
      <webElementGuid>2fb1b560-176a-4152-83b8-090b1478e5f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
