<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_checkbox_budget</name>
   <tag></tag>
   <elementGuidId>305ffe80-01ed-4f52-993a-b67e742f859b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-block__medium-list_1' and @class='block__medium']//input[@type='checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.check-parts</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e9fd518-3196-4e81-bb9c-d5c49951c528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modal-login</value>
      <webElementGuid>975eedd9-a2b1-4bd1-b926-e8f915706fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>38ae414a-ac1e-4fd5-bef1-787ce8fafd10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>aa4c1aea-b6b8-4fdd-8bab-79b8a524686a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>会員ログイン</value>
      <webElementGuid>b14aecb5-4d71-4c28-aa0f-ba891dfc3c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global&quot;)/ul[1]/li[@class=&quot;nav-link--login&quot;]/a[1]</value>
      <webElementGuid>b15feb0d-1b41-4da0-964f-126b5a02f0af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='global']/ul/li[8]/a</value>
      <webElementGuid>556c4b35-ff8e-4094-b305-0ceeee413e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'会員ログイン')])[2]</value>
      <webElementGuid>932fd637-c785-4470-b9f9-d2472ad5dc1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='お問い合わせフォーム'])[1]/following::a[2]</value>
      <webElementGuid>0ac1d1da-ade6-4946-b0ee-c43efa17d735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='入札情報速報掲載'])[1]/preceding::a[1]</value>
      <webElementGuid>5fac14a7-ec16-4171-baec-dccaa1e1c84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[12]</value>
      <webElementGuid>e189cb82-0392-4aaf-ad60-649ca70180a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>d7cf20ba-a6a4-48d0-92ff-66f1fa180f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '会員ログイン' or . = '会員ログイン')]</value>
      <webElementGuid>673fe253-7ba0-4c78-a0ce-8c4cbe92867a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
