<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_menu_Anken</name>
   <tag></tag>
   <elementGuidId>4f485b56-fc8d-47f5-ad92-a8e44f015d4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>li.authed-gnav__item:nth-child(5)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fc3c907c-93a8-4923-be79-3c8def4bcf1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/usermenu/bookmark_anken/</value>
      <webElementGuid>95b77fd8-1f12-4031-bd8f-5cd977456a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ブックマーク</value>
      <webElementGuid>57954415-91bc-4715-ae04-cdf6182300f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gnav&quot;)/ul[@class=&quot;authed-gnav&quot;]/li[@class=&quot;authed-gnav__item&quot;]/a[1]</value>
      <webElementGuid>8c3f778d-e2e1-4ec5-a9ca-d8eaa494b152</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='gnav']/ul/li[5]/a</value>
      <webElementGuid>fe3e0711-aa58-4457-ba1a-b7fcf94633a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='関連落札メール配信案件指定確認・編集'])[1]/following::a[1]</value>
      <webElementGuid>02119d01-a715-4fde-86a8-036096189611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(入札メール配信設定)（関連落札メール配信案件指定）'])[1]/following::a[2]</value>
      <webElementGuid>a32853b4-0211-47dc-863c-6d89c7372af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='関連落札メール配信案件指定 確認・編集'])[1]/preceding::a[1]</value>
      <webElementGuid>fa4ac811-e7ac-4051-9edd-f5c216002c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/usermenu/bookmark_anken/')])[2]</value>
      <webElementGuid>1e58a521-21d1-4f17-8475-493cedbc5802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/nav/ul/li[5]/a</value>
      <webElementGuid>dcad36d4-137c-42cc-8fdb-5963059c29b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/usermenu/bookmark_anken/' and (text() = 'ブックマーク' or . = 'ブックマーク')]</value>
      <webElementGuid>32a5de34-59e1-47fd-af70-51eefe96776d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
