<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_menu_Yotei</name>
   <tag></tag>
   <elementGuidId>4041de96-6ecc-42d1-a9be-4574f66c40b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.authed-gnav__item:nth-child(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='gnav']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ea56fbd-e896-448f-9e01-56e006134085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/yotei_search</value>
      <webElementGuid>51b6e2ee-5a0f-436a-b4b5-dd785e614779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              予定情報検索(予定情報メール配信設定)
            </value>
      <webElementGuid>a045d428-9ec9-45b9-8ac8-c38c29f29496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gnav&quot;)/ul[@class=&quot;authed-gnav&quot;]/li[@class=&quot;authed-gnav__item global_02&quot;]/a[1]</value>
      <webElementGuid>ea26ef07-37a0-4e65-a757-0003a7e29085</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='gnav']/ul/li[2]/a</value>
      <webElementGuid>65409c2b-75a1-4a72-a34a-2f2fcf9d1a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='予算書情報検索'])[1]/following::a[1]</value>
      <webElementGuid>f1154612-eefe-4254-a771-1a0a97fab6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='契約・登録情報'])[1]/following::a[3]</value>
      <webElementGuid>24e3cb4d-1ba5-4bbb-bbdc-32da7ceee430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/yotei_search')]</value>
      <webElementGuid>40a30178-c2c4-472b-8128-d2537c4d80f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a</value>
      <webElementGuid>0b95cdd3-c93a-4078-93da-dc90924bcffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/yotei_search' and (text() = '
              予定情報検索(予定情報メール配信設定)
            ' or . = '
              予定情報検索(予定情報メール配信設定)
            ')]</value>
      <webElementGuid>c40c6852-e206-42e5-ac8d-4bcc72f1aaa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
