<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_menu_Both</name>
   <tag></tag>
   <elementGuidId>381e366d-fadc-408e-9bea-46bc063d884f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.authed-gnav__item:nth-child(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='gnav']/ul/li[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3e9f3685-b7c4-47a6-b87a-a712f9820e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>authed-gnav__item-inner menu-big</value>
      <webElementGuid>f42e6393-a55a-4b34-a260-4b7462465314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>入札・落札情報検索 (入札メール配信設定)（関連落札メール配信案件指定）</value>
      <webElementGuid>1145ecd0-6e06-4d9b-a4bd-88ac5763c918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gnav&quot;)/ul[@class=&quot;authed-gnav&quot;]/li[@class=&quot;authed-gnav__item  is-current&quot;]/a[1]/span[@class=&quot;authed-gnav__item-inner menu-big&quot;]</value>
      <webElementGuid>3726556c-3325-4c36-be6d-c3bb0e05c2a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='gnav']/ul/li[3]/a/span</value>
      <webElementGuid>da7bf9d3-8e5b-47f1-a382-3230a0a1877c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(予定情報メール配信設定)'])[1]/following::span[1]</value>
      <webElementGuid>71e358c9-9f1e-4ea8-8610-22424df61846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='関連落札メール配信案件指定確認・編集'])[1]/preceding::span[1]</value>
      <webElementGuid>886780d9-6a6c-4f97-99f4-f838676108ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='入札・落札情報検索']/parent::*</value>
      <webElementGuid>5a8affcd-5ca7-4943-85b7-fdb0e7569767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span</value>
      <webElementGuid>75794362-32c2-4df3-9b01-3b712eeb38ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '入札・落札情報検索 (入札メール配信設定)（関連落札メール配信案件指定）' or . = '入札・落札情報検索 (入札メール配信設定)（関連落札メール配信案件指定）')]</value>
      <webElementGuid>f5f03f05-911f-4932-92bf-e0b0e76e5e73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
