<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_menu_Mail</name>
   <tag></tag>
   <elementGuidId>d9bfa37f-8969-4ee7-9a33-a1e482befcbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>li.authed-gnav__item:nth-child(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>38cc2ca4-f653-4b7b-8c96-89049589f25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/usermenu/rakusatsu_notice/</value>
      <webElementGuid>25513071-792c-42d7-b956-fb19104028e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>関連落札メール配信案件指定確認・編集</value>
      <webElementGuid>15621f40-3913-4fdc-870c-4e41c2f7c404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gnav&quot;)/ul[@class=&quot;authed-gnav&quot;]/li[@class=&quot;authed-gnav__item&quot;]/a[1]</value>
      <webElementGuid>67db9610-7104-4e18-98e1-b74ff2493f82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='gnav']/ul/li[4]/a</value>
      <webElementGuid>e1239183-23d0-429c-b60b-2ae5e50e6b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(入札メール配信設定)（関連落札メール配信案件指定）'])[1]/following::a[1]</value>
      <webElementGuid>112c14fc-beed-48ec-a577-2a2781034d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ブックマーク'])[2]/preceding::a[1]</value>
      <webElementGuid>15c6edf9-216d-40ed-b86a-c235c90d506f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/usermenu/rakusatsu_notice/')])[2]</value>
      <webElementGuid>818b1ab6-6153-49bc-a0f4-53e8fae485bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/nav/ul/li[4]/a</value>
      <webElementGuid>b79e0442-1f78-4cd7-b138-d4c4cd177b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/usermenu/rakusatsu_notice/' and (text() = '関連落札メール配信案件指定確認・編集' or . = '関連落札メール配信案件指定確認・編集')]</value>
      <webElementGuid>1921f2f0-6994-4df9-b55c-6c61e7382cc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
