<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>10f7bae2-0c64-4262-a026-bb3c59e866f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_logout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_logout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2a38a195-9688-4eb7-8f48-9db366dc736d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>34163f0c-bad1-4112-9574-188152b8a7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_logout</value>
      <webElementGuid>d7c3b6ea-9884-47a1-ac7b-e81fcb83716e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> ログアウト</value>
      <webElementGuid>028fe626-0717-4a22-bfde-f7cee6523669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_logout&quot;)</value>
      <webElementGuid>7f0a5996-3c05-4624-afaa-7c7199a27beb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_logout']</value>
      <webElementGuid>b4257697-1048-4641-bae4-b1c1a4931efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='global']/ul/li[8]/ul/li[11]/a</value>
      <webElementGuid>25f76cc9-1da1-4de6-a06a-340cab50c14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ログアウト')]</value>
      <webElementGuid>8e4f0d75-6b0d-42a1-a66f-b486dc8bd825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='お問い合わせ'])[2]/following::a[1]</value>
      <webElementGuid>18ddb89f-3a5d-43b3-850f-8de03b709e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='操作説明・資料'])[1]/following::a[2]</value>
      <webElementGuid>1820f1ca-1f84-4e8a-829e-538a571e14e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='予算書情報検索'])[1]/preceding::a[1]</value>
      <webElementGuid>f37128c5-7dac-445e-993a-3b8ac5f8ceec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ログアウト']/parent::*</value>
      <webElementGuid>cb877594-be17-4ac0-bf6c-67228b78ba91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[11]</value>
      <webElementGuid>243983d2-296a-44c4-976f-d7c794b22276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a</value>
      <webElementGuid>6eb1e307-c746-4ebd-889b-051286a3257f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'btn_logout' and (text() = ' ログアウト' or . = ' ログアウト')]</value>
      <webElementGuid>9d9c3d6a-ab23-444c-a355-ec218801936e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
