<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Login_Topmenu</name>
   <tag></tag>
   <elementGuidId>64e7d0cc-e2fe-4780-89dd-24d3510db99b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.nav-link--login > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='global']/ul/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d8480a79-0d18-46ac-84b1-696b383f1d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modal-login</value>
      <webElementGuid>8d05e4de-3380-48f9-8c5e-20892394c872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>69e045d8-70cb-43ab-bad4-22375ddebe9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>827f38b7-5617-4ec2-9d06-b12972f59264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>会員ログイン</value>
      <webElementGuid>dd821b6d-eef7-4831-9913-57782288e0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global&quot;)/ul[1]/li[@class=&quot;nav-link--login&quot;]/a[1]</value>
      <webElementGuid>d5befaa2-9f8c-43a8-ad6c-3e75a24732e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='global']/ul/li[8]/a</value>
      <webElementGuid>1743f968-0c45-4a04-8e86-e927af9a7493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'会員ログイン')])[2]</value>
      <webElementGuid>25346662-e06e-4e30-b6e3-3cc0b5a0485d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='お問い合わせフォーム'])[1]/following::a[2]</value>
      <webElementGuid>ba427080-b4bd-4349-bf96-9b9d142803c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='入札情報速報掲載'])[1]/preceding::a[1]</value>
      <webElementGuid>52361c41-7634-4373-a379-b9ce6da64648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[12]</value>
      <webElementGuid>445fa5a2-2ad6-45c7-907a-96b878d7b39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>aeb90e54-db16-4d33-9a6d-00dba39da67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '会員ログイン' or . = '会員ログイン')]</value>
      <webElementGuid>2a616f71-6f6e-4f37-a790-0804e826827a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
