<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Logout</name>
   <tag></tag>
   <elementGuidId>37189d7b-d685-4068-8f77-54ea7e1091de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_logout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_logout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
