<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_passWord</name>
   <tag></tag>
   <elementGuidId>526e2a08-b46e-4150-b09e-28798bda031c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#USER_PASSWORD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='USER_PASSWORD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5628c7f1-fd48-4532-8035-c7f3864666e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a9c0157e-ec40-4989-b3e4-a3f6176ad339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>USER_PASSWORD</value>
      <webElementGuid>65e4fb97-7f7a-4b4f-bef3-cf614e8f5396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USER_PASSWORD</value>
      <webElementGuid>df307c80-4fd6-4527-bfda-957d62b7f58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter password</value>
      <webElementGuid>8bc556bb-9e9b-4c6b-a4c3-fec33e410e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fafdcf0a-f4dc-40f4-8fe2-e7eb4ba12897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USER_PASSWORD&quot;)</value>
      <webElementGuid>69fa0abf-43eb-48ce-8603-56308718e903</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='USER_PASSWORD']</value>
      <webElementGuid>0844f82f-44c6-4335-b5fa-3eb1e7edda66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_login']/div[2]/div/input</value>
      <webElementGuid>1a8aba57-ced6-4e42-af57-ca404c5ac797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5926c504-6fd4-4e5e-b491-c0df19b9a52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'USER_PASSWORD' and @id = 'USER_PASSWORD' and @placeholder = 'Enter password' and @type = 'password']</value>
      <webElementGuid>18f47fd3-8dbe-4595-b2c6-9c007f9cc308</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
