<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_userName</name>
   <tag></tag>
   <elementGuidId>1fcc2e6e-3f37-421c-8696-bc4393e6973a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#USER_EMAIL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='USER_EMAIL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>862b25a4-7458-42aa-b0d1-ca0b35387d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2f1c3b71-401a-4305-b30e-0d7b612d6cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fc1850e1-e4d1-4dbe-b9ae-7c473be4c8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>USER_EMAIL</value>
      <webElementGuid>93929c5d-fb03-420d-bf20-10c57a3edd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USER_EMAIL</value>
      <webElementGuid>f562e855-92fb-401d-82c4-2bbe7c22b2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email</value>
      <webElementGuid>ac4565ba-26c6-4926-9f39-ece07c2a05b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USER_EMAIL&quot;)</value>
      <webElementGuid>f5ad1aa7-dc69-404d-ae0c-a8c782917ba7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='USER_EMAIL']</value>
      <webElementGuid>14dc1dbe-2e3d-4976-b6d6-13c731dc90d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_login']/div/div/input</value>
      <webElementGuid>c7da9d33-61b1-40b2-b9fd-0ca6e8d25dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>42602805-ce83-48bc-a8a1-ee364cd4abf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'USER_EMAIL' and @id = 'USER_EMAIL' and @placeholder = 'Enter your email']</value>
      <webElementGuid>9ad9e29f-9545-401a-b676-d82751fa6006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
