<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_area_Both</name>
   <tag></tag>
   <elementGuidId>0eb5c49c-ac5e-4b9b-b70c-c67473338d6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.nk-btn.both-item-search__btn--area.js-area-open</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='searchForm']/section[3]/div/div[2]/div/div/div[2]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c9544790-3f3a-412f-bea5-0f9a67099d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mode</name>
      <type>Main</type>
      <value>nyusatsu</value>
      <webElementGuid>339b9f64-2d42-4882-badf-3f2f1224b95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-btn both-item-search__btn--area js-area-open</value>
      <webElementGuid>f847fb4a-2717-4d22-a7d4-7ff33aa8d66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>発注地域を選択</value>
      <webElementGuid>c8c899af-e58c-44f4-abb5-692c487c8474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchForm&quot;)/section[@class=&quot;sec both-item-search js-nk-tab-menu-content&quot;]/div[@class=&quot;both-item-search__inner&quot;]/div[@class=&quot;both-item-search__f both-item-search__f--nyusatsu&quot;]/div[@class=&quot;both-item-search__f-box-wrap&quot;]/div[@class=&quot;both-item-search__f-box&quot;]/div[@class=&quot;both-item-search__f-box-r&quot;]/div[@class=&quot;both-item-search__area&quot;]/label[@class=&quot;nk-btn both-item-search__btn--area js-area-open&quot;]</value>
      <webElementGuid>71311930-948e-46ff-80f3-1ee6c6a55edf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchForm']/section[3]/div/div[2]/div/div/div[2]/div/label</value>
      <webElementGuid>3f35bd26-30d2-42c6-a0d5-8fd0d953dcdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='発注地域'])[1]/following::label[1]</value>
      <webElementGuid>0e4c5af4-d157-462e-ae21-6530a5dda3e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='業種カテゴリ'])[1]/preceding::label[1]</value>
      <webElementGuid>efb38190-ee5b-49dc-8069-085f3c79e679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label</value>
      <webElementGuid>57c81464-40e6-4418-b805-1c579fa97976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '発注地域を選択' or . = '発注地域を選択')]</value>
      <webElementGuid>e847719d-0828-4cd7-8472-b515d0f8880d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
