<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_checkALLitem_Categories_Both</name>
   <tag></tag>
   <elementGuidId>a1c4491f-17e4-4c84-9552-b1f2f49dad37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-category-on</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='js-category-on']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0d6a9a86-f8d9-42cb-ab43-9a89f7e1ec16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-category-on</value>
      <webElementGuid>2a7e6bde-57b9-4eb5-a01a-60e62612adcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>both-item-search__btn--check-on-all</value>
      <webElementGuid>ec79e7f7-4448-4b9d-9958-9f0ca9dc1a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-category-on&quot;)</value>
      <webElementGuid>e493b009-8f62-40fe-a307-6703d70ad49b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='js-category-on']</value>
      <webElementGuid>eea03a04-db7b-4ae3-9c1b-c2055200fbc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dataSearch']/div[2]/div/div/div/div/p[3]</value>
      <webElementGuid>9a86f20b-7171-4620-ac55-248fbabb1acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/p[3]</value>
      <webElementGuid>da18980d-f81e-4d15-be7b-09ea668d1aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'js-category-on']</value>
      <webElementGuid>e2911390-2e12-4c15-909e-2845ca186556</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
