<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_submitSelected_Area(c)</name>
   <tag></tag>
   <elementGuidId>55539855-4689-4e02-a7eb-fe0ae350ebab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-area-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='js-area-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5d2acab8-5f90-47a2-85f6-9de93694b8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-area-btn</value>
      <webElementGuid>68e9a774-96c6-454f-a07c-6b89854657af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-btn both-item-search__btn--submit</value>
      <webElementGuid>c167d10b-8f30-4cfc-918a-171a78f8c69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>変更する</value>
      <webElementGuid>2b6c0af6-e61e-4629-9f49-23320279cc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-area-btn&quot;)</value>
      <webElementGuid>16c3b4e2-bd5a-4e6a-ba0d-657987d697b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='js-area-btn']</value>
      <webElementGuid>70cacb40-89de-4282-b610-6a2cc7a656ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-area-list']/div/a</value>
      <webElementGuid>c50cb15a-ac7a-4418-a9c6-95f170b8b4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='沖縄県'])[1]/following::a[1]</value>
      <webElementGuid>c07af2aa-e8b3-4d17-aa6a-7dcf0c356769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='鹿児島県'])[1]/following::a[1]</value>
      <webElementGuid>3358a2b5-407b-44a5-b7ca-304824a4230e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='変更する'])[2]/preceding::a[1]</value>
      <webElementGuid>21316250-53ce-4dcb-a939-83145e6ddd5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/a</value>
      <webElementGuid>7fa93fb1-e54b-460f-ad92-ec1f30cdf887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'js-area-btn' and (text() = '変更する' or . = '変更する')]</value>
      <webElementGuid>17522e07-aaeb-4443-89d0-dc70a39f68ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
