<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_anken_Rakusatsu</name>
   <tag></tag>
   <elementGuidId>98354525-c0af-4f2c-8495-f2a55e747d2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//li[@onclick='change_search_type(this)'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9037b01d-1688-4d27-8394-6d14a82db2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mode</name>
      <type>Main</type>
      <value>rakusatsu</value>
      <webElementGuid>76fec291-11bd-4c7a-a68e-78c0306c5c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>change_search_type(this)</value>
      <webElementGuid>73f412d4-c7ec-4714-9ac1-79bac836df4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-tab-menu__item</value>
      <webElementGuid>5bee57ef-0f70-4bb8-b2df-df0b1edb616c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                落札情報のみ表示
                            </value>
      <webElementGuid>ac248e6f-577c-4107-8760-eb00ff713429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frm&quot;)/div[@class=&quot;item-search&quot;]/div[@class=&quot;bookmark-anken&quot;]/section[@class=&quot;nk-tab-menu__wrap&quot;]/ul[@class=&quot;js-nk-tab-menu nk-tab-menu tab_menu nk-tab-menu--4col&quot;]/li[@class=&quot;nk-tab-menu__item&quot;]</value>
      <webElementGuid>3d9b03eb-bea6-4f4d-8c15-e49856c14a0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//li[@onclick='change_search_type(this)'])[4]</value>
      <webElementGuid>6a454fbf-bb44-48a2-baf8-b72bb1171ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm']/div/div/section[2]/ul/li[4]</value>
      <webElementGuid>20a066bd-20b0-414f-9000-fe503f08e071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='入札情報のみ表示'])[1]/following::li[1]</value>
      <webElementGuid>2df1dd45-a779-4014-b226-0616e3c90002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='入札・落札同時に表示'])[1]/following::li[2]</value>
      <webElementGuid>cd8f1ff9-dd4d-487a-9b4a-64125e3f2208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/ul/li[4]</value>
      <webElementGuid>dbe5b0f7-68bb-4473-bfc2-086cf9dcc79f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
                                落札情報のみ表示
                            ' or . = '
                                落札情報のみ表示
                            ')]</value>
      <webElementGuid>03e99d97-ab8f-4e2b-9bf5-50aaa6f7e4e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
