<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_uncheckALLitem_Categorie_Both</name>
   <tag></tag>
   <elementGuidId>5be34bb9-983a-41da-8be9-90a077ccd179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-category-off</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='js-category-off']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>76559485-2d69-4311-849a-69aef67b67aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-category-off</value>
      <webElementGuid>8213fe93-74cb-4caa-a554-41d0d1d925fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>both-item-search__btn--check-off-all</value>
      <webElementGuid>ba47738e-ae4c-4140-9676-bdc2fa833c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-category-off&quot;)</value>
      <webElementGuid>a8194592-d4e7-471c-9d71-33a8cdaab55d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='js-category-off']</value>
      <webElementGuid>db752439-7f7b-46eb-a2a9-a5111d07251b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dataSearch']/div[2]/div/div/div/div/p[2]</value>
      <webElementGuid>8c781196-72e7-4df1-8344-bbdffc3e6fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/p[2]</value>
      <webElementGuid>d5362d1b-2596-456d-b5e8-cf7adcc8a3bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'js-category-off']</value>
      <webElementGuid>5623c7d6-8ef8-499f-aedd-e2b1e82b8224</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
