<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_submitSelected_Categories</name>
   <tag></tag>
   <elementGuidId>1fee08ae-a410-4af1-944c-94be50c15d89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-category-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='js-category-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0b70acd5-e23e-4b24-a3cc-7f0ae291eac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-category-btn</value>
      <webElementGuid>ee18e4bb-9214-466a-b116-6726f3c0ca13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-btn both-item-search__btn--submit</value>
      <webElementGuid>7ab4bb78-84f9-4e18-988f-2f49bdc814e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>変更する</value>
      <webElementGuid>e00198d6-8e0b-48b0-83ad-96ddee35a54f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-category-btn&quot;)</value>
      <webElementGuid>f2915a3a-ca32-479c-aad8-587547a31b75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='js-category-btn']</value>
      <webElementGuid>df42c289-956a-4aba-b1d2-f6999115d5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-category-list']/div/a</value>
      <webElementGuid>c7024408-cdd5-466b-bfd4-08949e3c97cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='電話・通信設備及び工事'])[1]/following::a[1]</value>
      <webElementGuid>e6b33ccf-11b8-4e2a-8232-7a937d40e52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='米軍案件'])[1]/following::a[1]</value>
      <webElementGuid>107bf1d2-b2fa-4439-9642-7999ea96a40a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='フリーワード検索を閉じる'])[1]/preceding::a[1]</value>
      <webElementGuid>d42da2be-2c4a-44da-b123-72924b798b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/a</value>
      <webElementGuid>4bd40aab-9597-4ece-ba4a-19bfe53a8481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'js-category-btn' and (text() = '変更する' or . = '変更する')]</value>
      <webElementGuid>893d2877-4442-42e2-9129-889ee46369f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
