<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_popupBugdet</name>
   <tag></tag>
   <elementGuidId>6ac5587d-7afc-404e-b5a2-b34632881d49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.search__btn--block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d38f897-8c63-41f6-a603-48d12704c0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-micromodal-trigger</name>
      <type>Main</type>
      <value>modal-organ</value>
      <webElementGuid>59568d3b-8e28-49cf-827a-e2755b70bbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search__btn--block</value>
      <webElementGuid>5b0803e9-c724-4cb4-9ca5-8f922af78a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eae5a013-8d18-41d2-85c4-818512832fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>機関選択</value>
      <webElementGuid>c63e2fa8-f2bc-4fd3-8104-677cbfa37230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchbox&quot;)/div[@class=&quot;search__title-wrap&quot;]/div[@class=&quot;search__inner&quot;]/div[@class=&quot;search__f&quot;]/div[@class=&quot;search__f-box-wrap&quot;]/div[@class=&quot;search__f-box&quot;]/div[@class=&quot;search__f-box-r&quot;]/div[@class=&quot;search__block&quot;]/div[@class=&quot;search__block-btn-wrap&quot;]/button[@class=&quot;search__btn--block&quot;]</value>
      <webElementGuid>cd073d13-9ec2-4348-9a4d-d985d3719f53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>b2f94f90-ca70-44a4-9ee1-d942580ecaba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchbox']/div/div/div/div[2]/div[2]/div[2]/div/div/button</value>
      <webElementGuid>b5112245-59b9-43cb-9338-b3906751ce29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='機関選択'])[1]/following::button[1]</value>
      <webElementGuid>3b4f953f-8524-4f44-9479-00cb08cbede3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='トライアル版は、過去3年度の予算書ファイルの検索、取得が可能です。'])[1]/following::button[1]</value>
      <webElementGuid>db166e55-1865-4845-83fa-002fb1e0712f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='検索キーワード'])[1]/preceding::button[1]</value>
      <webElementGuid>b611dd9c-c634-4e6c-961b-12d7c93116e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='検索する'])[1]/preceding::button[1]</value>
      <webElementGuid>546d4164-9774-45f8-8b00-62f5081795e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>1b4e603d-d6dc-4a06-a57d-74bf344fae1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '機関選択' or . = '機関選択')]</value>
      <webElementGuid>1d12f259-2b87-4119-a1e2-4d51f06fa1f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
