<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_checkAllItem_Budget</name>
   <tag></tag>
   <elementGuidId>1cf8c959-be45-4367-98b0-6ef4f9de9624</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#organ_select_all_on</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='organ_select_all_on']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2948d5a9-5287-4f12-9937-588c61dc9efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8fc926c6-17db-44a5-817b-6bea7881ecde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>organ_select_all_on</value>
      <webElementGuid>0046bbe4-1e68-4a47-8ab9-68ab8d520c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>全てを選択</value>
      <webElementGuid>6a17c013-11ba-4a28-a469-cdc1cdde3922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organ_select_all_on&quot;)</value>
      <webElementGuid>45c2dee2-0cfc-415c-b6eb-55ea02717834</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='organ_select_all_on']</value>
      <webElementGuid>89b85f86-4e05-45ad-beb8-6fc515ed1425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-organ']/div/div/header/button[2]</value>
      <webElementGuid>d642a3a0-3b8c-43fc-ba8d-85205b72f763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='全ての選択を解除'])[1]/following::button[1]</value>
      <webElementGuid>7bb61dbb-0ec1-4505-a79b-b44c49a22746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='発注機関選択'])[1]/following::button[2]</value>
      <webElementGuid>d6e2068c-7cb2-4ced-b830-3e38fc9aeaec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='変更する'])[1]/preceding::button[1]</value>
      <webElementGuid>98519cf7-ed5d-4a28-a6fb-63e4734e8a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='再検索'])[1]/preceding::button[1]</value>
      <webElementGuid>6080a069-63bb-4275-a83a-b50ac484764b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='全てを選択']/parent::*</value>
      <webElementGuid>bd11cab6-6c1f-4325-b10e-f345267c128c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>5101a89c-bea9-4913-9c0e-b0ecece01e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'organ_select_all_on' and (text() = '全てを選択' or . = '全てを選択')]</value>
      <webElementGuid>8fa7b0ad-ccca-4513-ba3b-f7bf61cfe881</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
