<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_uncheckAllItem_Bugdet</name>
   <tag></tag>
   <elementGuidId>b1bcb2d4-cd33-431c-9790-bdbc002f1a62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#organ_select_all_off</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='organ_select_all_off']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>32e94fa7-eee7-4eed-a93c-f11f8a2e5965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1cffc74-f2e0-4691-9b80-29c50bd5b061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>organ_select_all_off</value>
      <webElementGuid>f9cad4ec-388f-45c5-b2ef-2d1c806b4dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>全ての選択を解除</value>
      <webElementGuid>31df400e-1a7b-4fa0-a4df-b8d09f9cb879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organ_select_all_off&quot;)</value>
      <webElementGuid>de52e26d-49f7-4fa7-a14b-b2ab8391586b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='organ_select_all_off']</value>
      <webElementGuid>f9952482-d810-4932-8ec6-0200be6c04cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-organ']/div/div/header/button</value>
      <webElementGuid>5c95a2c0-0038-4a95-8bcb-18a4a45c6ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='発注機関選択'])[1]/following::button[1]</value>
      <webElementGuid>e9ef5a98-092f-47c2-aef7-822c25543720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='読み込み中'])[4]/following::button[1]</value>
      <webElementGuid>0a4a4b05-bdf3-48a4-b7f9-279bb943f2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='全てを選択'])[1]/preceding::button[1]</value>
      <webElementGuid>83a98402-19a5-4b73-95fb-f63a032049d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='変更する'])[1]/preceding::button[2]</value>
      <webElementGuid>a041f67b-1814-4cee-8b05-dc75fc62e24e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='全ての選択を解除']/parent::*</value>
      <webElementGuid>2e96d1b8-4d00-455b-bc03-b54eac75070e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/button</value>
      <webElementGuid>5a7068ca-cc8f-49c4-b66d-2936343f3bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'organ_select_all_off' and (text() = '全ての選択を解除' or . = '全ての選択を解除')]</value>
      <webElementGuid>048ef965-8993-4af7-ad2d-2aad04b4251a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
