<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_popup_listMail</name>
   <tag></tag>
   <elementGuidId>0105701a-d6a7-40a4-9971-b5157513acb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nk-btn.rakusatsu-notice-mail__btn.notice-mail-setting</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frm']/div/div/section/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e32a1ef-a9df-4e1d-86c2-e68355acd714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-btn rakusatsu-notice-mail__btn notice-mail-setting</value>
      <webElementGuid>799e2924-0780-4ef5-9cd9-3bb922916327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frm&quot;)/div[@class=&quot;item-search&quot;]/div[@class=&quot;rakusatsu-notice&quot;]/section[@class=&quot;sec&quot;]/div[@class=&quot;ttl-562-heading rakusatsu-notice__title-wrap&quot;]/div[@class=&quot;ttl-cnt&quot;]/div[@class=&quot;ttl-cnt--icon&quot;]/a[@class=&quot;nk-btn rakusatsu-notice-mail__btn notice-mail-setting&quot;]</value>
      <webElementGuid>fd574ee4-b698-4143-8eaf-3e26c7a575fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm']/div/div/section/div/div/div[2]/a</value>
      <webElementGuid>7fc2bf88-a13c-49ef-8acc-132f061f588e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/a</value>
      <webElementGuid>fc33eff0-0066-436a-9715-bdd63b73e724</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
