<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_()</name>
   <tag></tag>
   <elementGuidId>dd8f7672-b326-47e4-8936-271bd4eb1db6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='gnav']/ul/li[3]/a/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d2811cf3-6c07-411a-9800-17aea74b083c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>3b139aa1-7709-4994-8321-2d2e5c4d6fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(入札メール配信設定)（関連落札メール配信案件指定）</value>
      <webElementGuid>c3ee2fad-c631-44be-81d0-5dc66c1e90f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gnav&quot;)/ul[@class=&quot;authed-gnav&quot;]/li[@class=&quot;authed-gnav__item&quot;]/a[1]/span[@class=&quot;authed-gnav__item-inner menu-big&quot;]/div[@class=&quot;small&quot;]</value>
      <webElementGuid>a8254e35-ea49-4ce2-ab13-fea76569f5ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='gnav']/ul/li[3]/a/span/div</value>
      <webElementGuid>4d7801c1-e368-4057-8b10-bd06047e3ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(予定情報メール配信設定)'])[1]/following::div[1]</value>
      <webElementGuid>f202fee9-48b9-45ea-b3fb-7480de845a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='関連落札メール配信案件指定確認・編集'])[1]/preceding::div[1]</value>
      <webElementGuid>d0421192-afa1-429f-b2bb-6278654dc62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ブックマーク'])[2]/preceding::div[1]</value>
      <webElementGuid>38d245ab-1949-4451-9c72-589efbcbb094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='(入札メール配信設定)']/parent::*</value>
      <webElementGuid>137ea1ee-c2f6-47b4-b4e3-c651df45032d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span/div</value>
      <webElementGuid>2d4bf9ab-8223-454c-ba9b-07a881a5b78e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '(入札メール配信設定)（関連落札メール配信案件指定）' or . = '(入札メール配信設定)（関連落札メール配信案件指定）')]</value>
      <webElementGuid>af710d20-5797-49c0-a442-1d698ec6cc40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
