<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_USER_PASSWORD</name>
   <tag></tag>
   <elementGuidId>0b1fe8e5-17f5-4473-a0f1-4b9e9ca9c458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#USER_PASSWORD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='USER_PASSWORD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8618126b-451e-4873-80c3-3c7a6d712559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ad4d169c-308b-493d-ba1a-cdcb8d4eb975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>USER_PASSWORD</value>
      <webElementGuid>725bb140-bc15-4287-800b-6cf97a6ead36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USER_PASSWORD</value>
      <webElementGuid>b25bea8b-eac9-4a6c-be88-918b319e0913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter password</value>
      <webElementGuid>3995ad7b-112c-43fe-add6-e3b6b37103e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>56dbf27e-ada5-47ab-82c8-8604b588105c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USER_PASSWORD&quot;)</value>
      <webElementGuid>172ba886-5b3d-484d-a24f-85786ca5fbc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='USER_PASSWORD']</value>
      <webElementGuid>165f5965-ff37-40a3-b956-169fdd90be67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_login']/div[2]/div/input</value>
      <webElementGuid>de6c97e0-d587-4c28-973a-f84a2f342502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>7bb92612-df75-45f7-abdc-125ec71fe6f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'USER_PASSWORD' and @id = 'USER_PASSWORD' and @placeholder = 'Enter password' and @type = 'password']</value>
      <webElementGuid>b0a82241-b019-4d82-ad95-6d8c73020844</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
