<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address_USER_EMAIL</name>
   <tag></tag>
   <elementGuidId>30012053-f58e-409f-8dfe-6646a432a445</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#USER_EMAIL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='USER_EMAIL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1af737b0-9479-49d8-8616-e2067cb991f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>dfc2ec20-dbe7-4c13-b681-e8520483239d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>167c7257-85c3-4eab-8787-bf300d87913a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>USER_EMAIL</value>
      <webElementGuid>71af3296-0bb1-4f0c-b750-1a7e299f1039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>USER_EMAIL</value>
      <webElementGuid>94389867-f025-4e72-890a-8e027828c75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email</value>
      <webElementGuid>2d093d56-c6e2-431f-8ee3-5975d5b357a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;USER_EMAIL&quot;)</value>
      <webElementGuid>332bdd16-83aa-4f6c-9fa8-1085f7b87c48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='USER_EMAIL']</value>
      <webElementGuid>0668cc79-de3e-49db-89ed-51b6308c60b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_login']/div/div/input</value>
      <webElementGuid>333668b5-64e4-45cc-a83a-393217335fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>233b57e4-721c-40e0-b99f-409699acd1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'USER_EMAIL' and @id = 'USER_EMAIL' and @placeholder = 'Enter your email']</value>
      <webElementGuid>ec7b028f-fe7a-407b-8332-8b2dc75e65fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
