<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label__nk-modal__close js-modal-close</name>
   <tag></tag>
   <elementGuidId>fa2be5d3-0738-4804-a044-ab11808da94f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#message_modal > div.nk-modal__overlay > div.nk-modal__wrap.nk-modal__wrap.from-top.a-center.nk-form > label.nk-modal__close.js-modal-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='message_modal']/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c0119733-5e45-4ebe-a647-a31f37307463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>js-message</value>
      <webElementGuid>2fb00c3a-451d-4e71-89de-90dd1d7e55b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-modal__close js-modal-close</value>
      <webElementGuid>266f4280-ba4a-4e4b-827a-a6e509f554b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;message_modal&quot;)/div[@class=&quot;nk-modal__overlay&quot;]/div[@class=&quot;nk-modal__wrap nk-modal__wrap from-top a-center nk-form&quot;]/label[@class=&quot;nk-modal__close js-modal-close&quot;]</value>
      <webElementGuid>e1bd9d69-2a94-433c-bb36-a735674e4f0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='message_modal']/div/div/label</value>
      <webElementGuid>a2e9fdb0-2872-4109-9024-516f2ecf69ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/label</value>
      <webElementGuid>385a97ec-7066-4eca-bdda-1824572a64e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
