<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_leftitem3_Budget</name>
   <tag></tag>
   <elementGuidId>6385283e-81a5-4b87-9fec-f96b4c84ec16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#organ_high5 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='organ_high5']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>448c9422-f57a-4a5f-81fd-14435949925c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:scrollController.scrollTo('#js-block__medium-list_5')</value>
      <webElementGuid>cbfcf46b-9146-4615-b1b0-82ef56867d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>82094edb-524f-4736-b060-bcba497f0183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>区市町村</value>
      <webElementGuid>3da514c9-7890-434c-8442-a4bb8c1aff2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organ_high5&quot;)/a[1]</value>
      <webElementGuid>6a384a33-1ddc-4cb5-838b-8819a1b03f18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='organ_high5']/a</value>
      <webElementGuid>9977eada-3faf-4240-afbd-f97de50d1d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'区市町村')]</value>
      <webElementGuid>c488b82e-add2-45b6-bed1-7bee3927ecb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='都道府県庁'])[1]/following::a[1]</value>
      <webElementGuid>f52b2d41-3588-42f4-a37c-c6ea786be181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='中央省庁'])[1]/following::a[2]</value>
      <webElementGuid>9528cf8a-4f84-4bbf-8044-58dcd5f88251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='衆議院'])[1]/preceding::a[2]</value>
      <webElementGuid>28084e7d-47f8-488a-bb2b-761c25230758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='参議院'])[1]/preceding::a[2]</value>
      <webElementGuid>f84f728a-7b85-43a1-8caf-75a80903aafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='区市町村']/parent::*</value>
      <webElementGuid>71335558-a1d4-40bc-a3e8-73fab3617bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:scrollController.scrollTo('#js-block__medium-list_5')&quot;)]</value>
      <webElementGuid>18017300-0cde-42a3-936e-fa2a553e9122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/ul/li[3]/a</value>
      <webElementGuid>90273cfe-27c4-448e-b5f3-b92343bf5f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:scrollController.scrollTo(&quot; , &quot;'&quot; , &quot;#js-block__medium-list_5&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '区市町村' or . = '区市町村')]</value>
      <webElementGuid>e28b9cac-fa25-484b-9075-6e8b9c2d2385</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
