<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_both(Nyu_Raku)</name>
   <tag></tag>
   <elementGuidId>61ad8625-0d0c-4fe5-88a5-e6f098f299ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.nk-tab-menu__item-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='searchForm']/section[2]/ul/li/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e7f284c5-6ff9-4a28-9238-90085662002d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-tab-menu__item-inner</value>
      <webElementGuid>2963892b-8d23-401c-9551-5b2d9414f846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>入札・落札同時検索（入札メール配信設定）（関連落札メール配信案件指定）</value>
      <webElementGuid>a7419e32-4fbb-434e-90d3-bba3723aea7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchForm&quot;)/section[@class=&quot;nk-tab-menu__wrap&quot;]/ul[@class=&quot;js-nk-tab-menu nk-tab-menu&quot;]/li[@class=&quot;nk-tab-menu__item is-active&quot;]/span[@class=&quot;nk-tab-menu__item-inner&quot;]</value>
      <webElementGuid>85ebf267-b89b-4295-b3c9-ad404dccce00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchForm']/section[2]/ul/li/span</value>
      <webElementGuid>81f427c8-7480-4c69-85b1-a9a55fa87dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='保存した検索条件の呼び出し'])[1]/following::span[1]</value>
      <webElementGuid>1650dfe3-13b9-4524-b4da-6c1eb056d6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='入札・落札情報検索'])[1]/following::span[1]</value>
      <webElementGuid>df7a74f0-4158-4a75-bb8f-881328b81947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='入札情報のみ検索（入札メール配信設定）（関連落札メール配信案件指定）'])[1]/preceding::span[1]</value>
      <webElementGuid>5fda3510-f39a-4596-ab69-c70dd0eb6817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='落札情報のみ検索'])[1]/preceding::span[2]</value>
      <webElementGuid>d797fd2e-eff5-4d33-a656-ebf91558817c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='入札・落札同時検索']/parent::*</value>
      <webElementGuid>5ee2989b-d9ee-4c67-a34c-efa57e6a268e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/ul/li/span</value>
      <webElementGuid>3091b1a9-9c7d-47aa-8104-392e8c96480a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '入札・落札同時検索（入札メール配信設定）（関連落札メール配信案件指定）' or . = '入札・落札同時検索（入札メール配信設定）（関連落札メール配信案件指定）')]</value>
      <webElementGuid>5e6b65ad-6628-410b-9594-e1b5a4f14c4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
