<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1</name>
   <tag></tag>
   <elementGuidId>5bb89977-3f08-4378-b262-5551d9401b7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_form_submit > span.nk-btn-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_form_submit']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c4552d7a-029d-4d5d-85e0-6791003e1b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-btn-inner</value>
      <webElementGuid>4a6721f8-9e69-4412-ab90-eceb04a2e24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>検索する</value>
      <webElementGuid>6ef0784d-0846-4c4f-8d9a-5d9e0fb959d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_form_submit&quot;)/span[@class=&quot;nk-btn-inner&quot;]</value>
      <webElementGuid>2d5a7785-b258-4d35-8d43-5ef6c973dc01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='btn_form_submit']/span</value>
      <webElementGuid>9f0f51d0-8d4f-40de-adc7-1c1b3aafe552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='この検索条件で上書き保存'])[1]/following::span[1]</value>
      <webElementGuid>dd2bd660-860c-4223-a732-59f81f4255c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='入札予定情報検索結果'])[1]/preceding::span[1]</value>
      <webElementGuid>75fc7ee6-ae14-4619-bab9-8e54fbcd6569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='検索条件の編集に戻る'])[1]/preceding::span[1]</value>
      <webElementGuid>b26ec706-13ba-4c21-9d8f-40dda7983319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='検索する']/parent::*</value>
      <webElementGuid>8716ea9b-3b0a-4ee2-b834-1d9c8bba8de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/a/span</value>
      <webElementGuid>387b23e6-9f8a-4ab4-85f6-0f371c2998d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '検索する' or . = '検索する')]</value>
      <webElementGuid>6e0e7c34-fd34-4053-a3d3-4927603d06f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
