<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>8f529c42-b16c-48f7-aceb-a953c0153c1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nk-btn.yotei-search__btn--edit-saved.js-back2edit > span.nk-btn-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='searchResultPage']/section/div[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3dc54573-e4d8-4f20-85de-eb15ad1e860b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nk-btn-inner</value>
      <webElementGuid>ca145bb0-b987-4f7d-98a0-1e44ef9bc453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>検索条件の編集に戻る</value>
      <webElementGuid>673000c8-48ca-4fec-91fe-c469403a3d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResultPage&quot;)/section[@class=&quot;sec&quot;]/div[@class=&quot;yotei-search__result-btn-area&quot;]/a[@class=&quot;nk-btn yotei-search__btn--edit-saved js-back2edit&quot;]/span[@class=&quot;nk-btn-inner&quot;]</value>
      <webElementGuid>31383680-1e69-4043-907e-977137bc994f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchResultPage']/section/div[2]/a/span</value>
      <webElementGuid>a5ea597a-2ac0-40b5-88ed-8f04817e5226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='入札予定情報検索結果'])[1]/following::span[1]</value>
      <webElementGuid>67bf39db-e2c5-4168-8a1f-fd1782a34c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='検索する'])[1]/following::span[1]</value>
      <webElementGuid>a1204baa-6dac-4acb-bcd8-d3ae2722ad59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='案件名検索キーワード'])[2]/preceding::span[1]</value>
      <webElementGuid>05724d13-e7ae-4356-ae37-dab71208097d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='検索条件の編集に戻る']/parent::*</value>
      <webElementGuid>ddbba041-6ba3-4d80-b5e1-e9fccd21136f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/a/span</value>
      <webElementGuid>05247eb4-b225-4c27-aa70-ee76850f7f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '検索条件の編集に戻る' or . = '検索条件の編集に戻る')]</value>
      <webElementGuid>8532631b-fddd-45eb-ac0d-30691f1607e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
