<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_menu_budget</name>
   <tag></tag>
   <elementGuidId>31918133-135d-42af-9e3d-ccdc88dd9090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.authed-gnav__item > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='gnav']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>368ec152-3720-44cc-8285-0f2c29be46ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/usermenu/budget_search/</value>
      <webElementGuid>118575f3-2cd0-4115-b772-59e67c850bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>予算書情報検索</value>
      <webElementGuid>0c88f96d-a5e0-4384-8596-3fd5feb90c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gnav&quot;)/ul[@class=&quot;authed-gnav&quot;]/li[@class=&quot;authed-gnav__item&quot;]/a[1]</value>
      <webElementGuid>5cb519ff-7c2b-4612-9c90-14517b14481f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='gnav']/ul/li/a</value>
      <webElementGuid>70f128e7-ea57-416e-8192-d1ef629b7b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='お問い合わせ'])[2]/following::a[2]</value>
      <webElementGuid>2eff551e-8c99-4194-8611-22bfb6246711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='操作説明・資料'])[1]/following::a[3]</value>
      <webElementGuid>b5f80ffc-f0c3-4aea-bb62-af7348fece7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/usermenu/budget_search/')])[2]</value>
      <webElementGuid>15f8a76b-bff8-4a7b-be12-53eab2ec1289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/nav/ul/li/a</value>
      <webElementGuid>9cc825d9-c7e5-498a-b370-0faace1a1685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/usermenu/budget_search/' and (text() = '予算書情報検索' or . = '予算書情報検索')]</value>
      <webElementGuid>99a84ddc-abaa-4eef-a421-b440bc026bf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
