<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_menu_Anken</name>
   <tag></tag>
   <elementGuidId>4f485b56-fc8d-47f5-ad92-a8e44f015d4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='gnav']/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8096fe9b-3128-4775-bc57-c4062a56490e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/usermenu/bookmark_anken/</value>
      <webElementGuid>e3137cfa-19e1-48a8-b293-de4ce6e0aadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ブックマーク</value>
      <webElementGuid>e6270bae-d9e9-4a85-b55c-dc8b3988417c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gnav&quot;)/ul[@class=&quot;authed-gnav&quot;]/li[@class=&quot;authed-gnav__item&quot;]/a[1]</value>
      <webElementGuid>9ac02d48-8c03-4eb0-81ad-6a3bc4ada356</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='gnav']/ul/li[5]/a</value>
      <webElementGuid>f26f4755-b8a4-4260-bc30-c5005fed35e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='関連落札メール配信案件指定確認・編集'])[1]/following::a[1]</value>
      <webElementGuid>f4c969aa-46d5-48a9-80f3-d1daf3ae99f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(入札メール配信設定)（関連落札メール配信案件指定）'])[1]/following::a[2]</value>
      <webElementGuid>0d4e7a3a-6a4b-491b-b68f-d3f7b6c873e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='関連落札メール配信案件指定 確認・編集'])[1]/preceding::a[1]</value>
      <webElementGuid>26ece133-49fc-4a60-86ef-f3714e43e64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/usermenu/bookmark_anken/')])[2]</value>
      <webElementGuid>1d088745-4aaa-44f3-85b7-54e70f79afe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/nav/ul/li[5]/a</value>
      <webElementGuid>966c9325-72ed-48f0-b8f2-4d5aff1b699b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/usermenu/bookmark_anken/' and (text() = 'ブックマーク' or . = 'ブックマーク')]</value>
      <webElementGuid>398c656a-6ca6-43c7-9aba-e7cb2186cf3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
