<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_menu_Yotei</name>
   <tag></tag>
   <elementGuidId>4041de96-6ecc-42d1-a9be-4574f66c40b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.authed-gnav__item.global_02 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='gnav']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0b3da042-1910-410f-9607-75885a70ff8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/yotei_search</value>
      <webElementGuid>c7565130-1a6d-4bb8-b559-cc44b9d197fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              予定情報検索(予定情報メール配信設定)
            </value>
      <webElementGuid>46564f9d-b456-4182-aeb7-fa7467670c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gnav&quot;)/ul[@class=&quot;authed-gnav&quot;]/li[@class=&quot;authed-gnav__item global_02&quot;]/a[1]</value>
      <webElementGuid>35b56b5e-5011-44d5-b3a5-70d9e9b2239f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='gnav']/ul/li[2]/a</value>
      <webElementGuid>dbed8f68-5bd7-4965-97ec-4434d762cb73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='予算書情報検索'])[1]/following::a[1]</value>
      <webElementGuid>cc4fc55e-c70e-415a-bf37-65e3adf11a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='契約・登録情報'])[1]/following::a[3]</value>
      <webElementGuid>d1ddd153-f836-4c29-a124-c1d8dbb93d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/yotei_search')]</value>
      <webElementGuid>ead7cfff-704b-4801-ba4f-0e5f9f5b8239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a</value>
      <webElementGuid>15ca8e97-ee71-4e6f-8d10-de0b790011cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/yotei_search' and (text() = '
              予定情報検索(予定情報メール配信設定)
            ' or . = '
              予定情報検索(予定情報メール配信設定)
            ')]</value>
      <webElementGuid>a248c1b9-55ea-4225-8d22-b6ddd89b7f71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
