<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_menu_Both</name>
   <tag></tag>
   <elementGuidId>381e366d-fadc-408e-9bea-46bc063d884f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.authed-gnav__item.is-current > a > span.authed-gnav__item-inner.menu-big</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='gnav']/ul/li[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1e9acbb4-0de3-48e0-9f6c-92460ce9d7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>authed-gnav__item-inner menu-big</value>
      <webElementGuid>72720cfa-6ab2-4a00-84be-5f8dc2a8a617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>入札・落札情報検索 (入札メール配信設定)（関連落札メール配信案件指定）</value>
      <webElementGuid>6e86bd14-2a95-4d56-80f6-8a0097293d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gnav&quot;)/ul[@class=&quot;authed-gnav&quot;]/li[@class=&quot;authed-gnav__item  is-current&quot;]/a[1]/span[@class=&quot;authed-gnav__item-inner menu-big&quot;]</value>
      <webElementGuid>7dff4c73-908e-4da6-a37c-eb77174834a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='gnav']/ul/li[3]/a/span</value>
      <webElementGuid>d09414a8-e49b-4bde-84fd-eaa807bfc1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(予定情報メール配信設定)'])[1]/following::span[1]</value>
      <webElementGuid>c1c9c783-0131-4603-9257-87250e19f9ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='関連落札メール配信案件指定確認・編集'])[1]/preceding::span[1]</value>
      <webElementGuid>e37d4e72-bb93-465f-9c89-c4baecbd35e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='入札・落札情報検索']/parent::*</value>
      <webElementGuid>fefef8c3-c0bc-4d76-a9a7-cded6755efdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span</value>
      <webElementGuid>5f72b515-e7b9-4773-ae11-41f4703a87d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '入札・落札情報検索 (入札メール配信設定)（関連落札メール配信案件指定）' or . = '入札・落札情報検索 (入札メール配信設定)（関連落札メール配信案件指定）')]</value>
      <webElementGuid>cfaa7592-2a9d-43d7-9426-a7aa14be5f68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
