<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_InputKW_Budget</name>
   <tag></tag>
   <elementGuidId>40f29c89-3dae-4eee-a1e7-5fef4a0e9e99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchValue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchValue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4bbd32a-37eb-42af-9da4-c2474d09716a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchValue</value>
      <webElementGuid>7f37d310-9418-42f5-868b-2d4d5aa3cd3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchValue</value>
      <webElementGuid>88970092-c179-4c2f-bdac-bf03347866c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchValue&quot;)</value>
      <webElementGuid>3d7893ed-abab-48c8-9d71-062eac1a8d39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchValue']</value>
      <webElementGuid>ae407780-0b93-426c-8d5e-10e646f9c378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchbox']/div/div/div/div[2]/div[3]/div[2]/div/div/input</value>
      <webElementGuid>8e5f0d24-b872-44ec-9338-f52912e5fa71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>6295b212-3de9-40e6-91c3-f67800f1241d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'searchValue' and @id = 'searchValue']</value>
      <webElementGuid>734d1cda-a4fd-4f66-9946-12af00b81227</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
