<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_submit_Login</name>
   <tag></tag>
   <elementGuidId>a8da7ddb-1c67-41db-a572-4f00b858050f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Login&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76e2c0cc-5a90-4193-b710-97ce91a2704c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>40abd4c1-9d57-4065-9710-9f158ecfd7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.nyusatsu-king.com/CONTENT/admin/css/images/admin_login_btn.gif</value>
      <webElementGuid>c97eb9d1-6587-403b-9c98-9be656ab865f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>933ff9ed-4c19-4c5f-a67d-b2b98147d0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>98a4476f-16b4-4c35-914d-8fb574c3adf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/div[@class=&quot;pnl_login&quot;]/table[1]/tbody[1]/tr[1]/td[1]/div[@class=&quot;text-center&quot;]/button[1]/input[1]</value>
      <webElementGuid>9935561d-1bd2-4638-a66e-3ab278621b0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Login']</value>
      <webElementGuid>8f25b005-023e-46fc-b28c-598eb6583339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/div/table/tbody/tr/td/div[2]/button/input</value>
      <webElementGuid>a1e1ea5e-6082-465b-a23f-67f785090394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/input</value>
      <webElementGuid>711ac268-59a4-4c27-a448-c4f73b705d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @src = 'https://www.nyusatsu-king.com/CONTENT/admin/css/images/admin_login_btn.gif' and @alt = 'Login' and @name = 'Login']</value>
      <webElementGuid>fc2a6f39-5adf-4a4d-b698-9d400fc1afd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
