<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_passWord</name>
   <tag></tag>
   <elementGuidId>30146a34-37fc-4fd6-b06e-5ec30920fa55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ADMIN_PWD']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ADMIN_PWD</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f50678e6-ffd4-4487-99f3-01cd8837e7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a0291eaf-1e38-4fc1-ab2b-31e547d0f802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ADMIN_PWD</value>
      <webElementGuid>5cf4bd2e-d64c-458e-9acb-7955b8f53e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>204419cf-8666-43cb-b58b-95c899663ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ADMIN_PWD</value>
      <webElementGuid>fcb3c7f3-3831-4069-8a19-182d004b92f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ef835364-d2aa-4e40-b89d-b79e03ae72d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ADMIN_PWD&quot;)</value>
      <webElementGuid>81bf3969-c67a-49ea-9935-9b0ed3c7451c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ADMIN_PWD']</value>
      <webElementGuid>baa2b19d-9ab0-4599-8c8b-6bfc419dce82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/div/table/tbody/tr/td/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>f72cab1f-940a-4624-972d-771a59cf0b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>95423d18-b2e7-48a4-9d69-8801e38ea779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'ADMIN_PWD' and @id = 'ADMIN_PWD']</value>
      <webElementGuid>5c634bde-e0eb-4476-904c-e74796ed3c4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
